#unalias -a
alias ls='ls -G'
alias l='ls -lA'
alias g='grep -I'
alias llrt='ls -lrt'
alias llrtt='ls -lrt | tail'
alias lt='ls -lrt | tail'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias reload='if [[ "$SHELL" == "/bin/zsh" ]] ; then . ~/.zshrc ; else . ~/.bash_profile ; fi'
alias jcat='unzip -p'
alias sep='printf "${FG_BLUE}${BG_CYAN}% $(( COLUMNS / 2 + 10 ))s% $(( COLUMNS - COLUMNS / 2 - 10 ))s${NO_COLOR}\n" "$(date +"%Y-%m-%d  %T")" ""'
